TDP-2811 update voice url
Bandwidth/bandwidth.github.io pull request #178
Opened 2019-07-22 12:11 UTC by rmello-daitan

## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `gitbook` 

- [ ] I made sure that the site looks great and functions perfectly live
- [ ] I ran splell check
- [ ] I'm ready for these changes to be made live

## For the Reviewer

### General Review

- [ ] All changes/updates requested were intentionally changed or added (no extraneous file or partial updates)
- [ ] The live rendered page behaves and looks like intended.
- [ ] All links work as intended. (click every link to make sure that it takes the user to the expected place).
- [ ] The markdown was rendered to HTML as intended. (Tables look right, code samples are gated properly).
- [ ] Any style or CSS changes are tested on multiple different pages to ensure nothing unexpected broke or changed.
- [ ] I proof-read the live site (`gitbook serve`) and there are no oblivious splelling or grammer misteaks.

### Gitbook Specific

- [ ] Any new documentation pages have been added to the `SUMMARY.md` file so they are rendered to HTML.
- [ ] Any links to other pages within this documentation use relative links (`[read more about ...](guides/voice/voicemail.md)`).
- [ ] Gitbook can install and build the documentation (`gitbook install` & `gitbook build`)

### Code Specific

- [ ] All code has been tested against the live API.
- [ ] All code can be run without throwing errors or **new** warnings.
- [ ] All code is formatted correctly and consistently (spaces, tabs).
- [ ] All code is legible and idiomatic to the language.
- [ ] All code uses sensical method, function, and variable names.
- [ ] All code samples use the appropriate syntax highlighting.
- [ ] Any examples re-use same phone numbers, uuids, variable names, etc... throughout (IE don't have something like `{from: '+19191231234', to: '+19191231234'}` unless it's meant to show the same phone number calling/texting itself ).

## TL;DR

- [ ] I did these things
- [ ] I'm ready for these changes to be made live

2019-07-22 12:15 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-TDP-2811-update-voice-url.s3-website-us-east-1.amazonaws.com/

2019-07-22 13:23 UTC, muesono-daitan commented
There are urls referencing api.catapult.inetwork.com. I don't know if there is a jira for this or if it should be fixed in this PR though.

2019-07-22 13:33 UTC, jmulford-bandwidth commented
> There are urls referencing api.catapult.inetwork.com. I don't know if there is a jira for this or if it should be fixed in this PR though.

We caught this in DX-537 (stopgap docsite audit) and will be making a separate jira for it. Thanks for reassuring it!

2019-07-22 13:44 UTC, rmello-daitan commented
> > There are urls referencing api.catapult.inetwork.com. I don't know if there is a jira for this or if it should be fixed in this PR though.
> 
> We caught this in DX-537 (stopgap docsite audit) and will be making a separate jira for it. Thanks for reassuring it!

Oh, I was going to fix it. It is just in the README.md file. We need to fix the "Make a call" examples as well. They are missing `answerUrl` and `applicationId`

2019-07-22 13:48 UTC, jmulford-bandwidth commented
> > > There are urls referencing api.catapult.inetwork.com. I don't know if there is a jira for this or if it should be fixed in this PR though.
> > 
> > 
> > We caught this in DX-537 (stopgap docsite audit) and will be making a separate jira for it. Thanks for reassuring it!
> 
> Oh, I was going to fix it. It is just in the README.md file. We need to fix the "Make a call" examples as well. They are missing `answerUrl` and `applicationId`

I just spoke with @dtolb and we're gonna revamp that whole home page for this launch so no need to update that

2019-07-22 15:06 UTC, dtolb commented
> > > > There are urls referencing api.catapult.inetwork.com. I don't know if there is a jira for this or if it should be fixed in this PR though.
> > > 
> > > 
> > > We caught this in DX-537 (stopgap docsite audit) and will be making a separate jira for it. Thanks for reassuring it!
> > 
> > 
> > Oh, I was going to fix it. It is just in the README.md file. We need to fix the "Make a call" examples as well. They are missing `answerUrl` and `applicationId`
> 
> I just spoke with @dtolb and we're gonna revamp that whole home page for this launch so no need to update that

https://github.com/Bandwidth/bandwidth.github.io/pull/179 Covers changes

2019-07-22 18:14 UTC, dtolb requested changes
@rmello-daitan 

Per TDP-2824 the voice url in it's entirety should be 
`https://voice.bandwidth.com/api/v2/accounts/{{accountId}}/calls`

and then `https://voice.bandwidth.com/api/v2/accounts/{{accountId}}/calls/{{callId}}`

There are a few places in this PR where the old url had `.../api/v2/users/` that were fixed that should be updated correctly.

2019-07-22 18:14 UTC, dtolb commented on voice/bxml/callBacks/answer.md
> -	"callUrl": "https://voice.bandwidth.com/api/v2/users/55555555/calls/3C5F8A8B-CDA2-443A-B797-B3ADA2197E05"
See the new TDP-2824

2019-07-22 18:21 UTC, rmello-daitan commented
> @rmello-daitan
> 
> Per TDP-2824 the voice url in it's entirety should be
> `https://voice.bandwidth.com/api/v2/accounts/{{accountId}}/calls`
> 
> and then `https://voice.bandwidth.com/api/v2/accounts/{{accountId}}/calls/{{callId}}`
> 
> There are a few places in this PR where the old url had `.../api/v2/users/` that were fixed that should be updated correctly.

yep, just saw it. I'll update the code

2019-07-22 18:49 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-TDP-2811-update-voice-url.s3-website-us-east-1.amazonaws.com/

2019-07-22 19:53 UTC, jmulford-bw approved these changes

2019-07-22 20:46 UTC, dtolb approved these changes

2019-07-23 14:17 UTC, mrmeyers99 approved these changes

2019-07-23 15:41 UTC, merged