Dx 618
Bandwidth/bandwidth.github.io pull request #205
Opened 2019-08-12 19:01 UTC by jmulford-bandwidth

## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `gitbook` 

- [ ] I made sure that the site looks great and functions perfectly live
- [ ] I ran splell check
- [ ] I'm ready for these changes to be made live

## For the Reviewer

### General Review

- [ ] All changes/updates requested were intentionally changed or added (no extraneous file or partial updates)
- [ ] The live rendered page behaves and looks like intended.
- [ ] All links work as intended. (click every link to make sure that it takes the user to the expected place).
- [ ] The markdown was rendered to HTML as intended. (Tables look right, code samples are gated properly).
- [ ] Any style or CSS changes are tested on multiple different pages to ensure nothing unexpected broke or changed.
- [ ] I proof-read the live site (`gitbook serve`) and there are no oblivious splelling or grammer misteaks.

### Gitbook Specific

- [ ] Any new documentation pages have been added to the `SUMMARY.md` file so they are rendered to HTML.
- [ ] Any links to other pages within this documentation use relative links (`[read more about ...](guides/voice/voicemail.md)`).
- [ ] Gitbook can install and build the documentation (`gitbook install` & `gitbook build`)

### Code Specific

- [ ] All code has been tested against the live API.
- [ ] All code can be run without throwing errors or **new** warnings.
- [ ] All code is formatted correctly and consistently (spaces, tabs).
- [ ] All code is legible and idiomatic to the language.
- [ ] All code uses sensical method, function, and variable names.
- [ ] All code samples use the appropriate syntax highlighting.
- [ ] Any examples re-use same phone numbers, uuids, variable names, etc... throughout (IE don't have something like `{from: '+19191231234', to: '+19191231234'}` unless it's meant to show the same phone number calling/texting itself ).

## TL;DR

- [ ] I did these things
- [ ] I'm ready for these changes to be made live

2019-08-12 19:05 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-02 15:42 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-02 15:44 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-03 13:50 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-03 13:59 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-03 15:23 UTC, ghost requested changes

2019-10-03 15:23 UTC, dtolbert-bw commented on README.md
> +messaging_client = bandwidth_client.messaging_client.client
For brevity sake, we can leave out initialization from the Readme snips.

2019-10-03 15:23 UTC, dtolbert-bw commented on README.md
> +voice_client = bandwidth_client.voice_client.client
For brevity sake, we can leave out initialization from the Readme snips

2019-10-03 19:53 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-09 17:23 UTC, ghost approved these changes

2019-10-09 17:58 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-DX-618.s3-website-us-east-1.amazonaws.com/

2019-10-09 20:31 UTC, ghost approved these changes

2019-10-09 20:37 UTC, merged