Aj docs update
Bandwidth/bandwidth.github.io pull request #418
Opened 2020-06-09 15:18 UTC by ajrice6713

## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes
Added documentation that covers setting a Final Destination/Failover URI

2020-06-09 15:23 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-AJ-Docs-Update.s3-website-us-east-1.amazonaws.com/

2020-06-09 19:15 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-AJ-Docs-Update.s3-website-us-east-1.amazonaws.com/

2020-06-10 21:30 UTC, dtolb commented on numbers/guides/managingLineFeatures.md
> +```
Include ` ```http` to get nice formatting

```http
PUT https://dashboard.bandwidth.com/api/account/{accountId}/sites/{siteId}/sippeers/{sippeerId}
Authorization: Basic {base64_encoded_credentials)
Content-Type: application/xml
<SipPeer>
 <PeerName>{location_name}</PeerName>
 <FinalDestinationUri>{final_destination}</FinalDestinationUri>
 <IsDefaultPeer>true</IsDefaultPeer>
</SipPeer>
```

2020-06-10 21:30 UTC, dtolb commented on numbers/guides/managingLineFeatures.md
> +```
Same as above

2020-06-10 21:30 UTC, dtolb requested changes
add ` ```http ` to code samples for syntax highlighting

2020-06-11 11:58 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-AJ-Docs-Update.s3-website-us-east-1.amazonaws.com/

2020-06-11 14:06 UTC, merged

2020-06-11 14:07 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-AJ-Docs-Update.s3-website-us-east-1.amazonaws.com/