updated stale links
Bandwidth/bandwidth.github.io pull request #586
Opened 2021-01-06 19:29 UTC by jmulford-bw

## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

2021-01-06 19:54 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-task-update-postman-oas-links.s3-website-us-east-1.amazonaws.com/index.html

2021-04-06 13:53 UTC, ajrice6713 approved these changes

2021-04-06 13:53 UTC, hamermike requested changes

2021-04-06 13:53 UTC, hamermike commented on SUMMARY.md
> +	* [OpenAPI/Swagger on Github](https://github.com/Bandwidth/openapi-specs)
```suggestion
	* [Examples on GitHub](https://github.com/bandwidth-samples)
	* [OpenAPI/Swagger on GitHub](https://github.com/Bandwidth/openapi-specs)
```

2021-04-06 13:53 UTC, hamermike commented on sdks/about.md
> +| [OpenAPI/Swagger on Github](https://github.com/Bandwidth/openapi-specs) | Bandwidth's [Open API Specification](https://swagger.io/solutions/getting-started-with-oas/) files |
```suggestion
| [Examples on GitHub](https://github.com/bandwidth-samples)                                 | Example applications & Scripts demo-ing Bandwidth functionality with the SDKs                      |
| [OpenAPI/Swagger on GitHub](https://github.com/Bandwidth/openapi-specs) | Bandwidth's [Open API Specification](https://swagger.io/solutions/getting-started-with-oas/) files |
```

2021-04-06 13:56 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-task-update-postman-oas-links.s3-website-us-east-1.amazonaws.com/index.html

2021-04-06 13:56 UTC, hamermike approved these changes

2021-04-06 13:57 UTC, merged

2021-04-06 14:01 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-task-update-postman-oas-links.s3-website-us-east-1.amazonaws.com/index.html