Global TN Search Guide
Bandwidth/bandwidth.github.io pull request #588
Opened 2021-01-06 19:31 UTC by jchavez443

2021-01-06 20:06 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-tns-guide.s3-website-us-east-1.amazonaws.com/index.html

2021-01-06 21:05 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-tns-guide.s3-website-us-east-1.amazonaws.com/index.html

2021-01-07 13:37 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-tns-guide.s3-website-us-east-1.amazonaws.com/index.html

2021-01-07 14:49 UTC, jmulford-bw approved these changes

2021-01-07 14:55 UTC, hamermike requested changes
Tiny change.

2021-01-07 14:55 UTC, hamermike commented on numbers/guides/globalTnSearch.md
> +> When querying for a phone number that is NOT in your account you will recieve an error `Telephone Numbers cannot be found on accounts`.  Within an `<ErrorList>` XML list.
```suggestion
> When querying for a phone number that is NOT in your account you will receive an error `Telephone Numbers cannot be found on accounts`.  Within an `<ErrorList>` XML list.
```

2021-01-07 14:55 UTC, hamermike commented on numbers/guides/globalTnSearch.md
> +Retrieves information about the specified telephone number. The information returned provides status and historic information about the Telephone Number, including the status, the order id and date a
```suggestion
Retrieves information about the specified telephone number. The information returned provides status and historic information about the Telephone Number, including the status, the order id and date associated with the last modification, and the account and site information associated with the TN. The request for more information can be made by requesting a number of specific derived sub-resources.
```

2021-01-07 15:32 UTC, ajrice6713 approved these changes

2021-01-07 16:00 UTC, jchavez443 commented on numbers/guides/globalTnSearch.md
> +Retrieves information about the specified telephone number. The information returned provides status and historic information about the Telephone Number, including the status, the order id and date a
How did you even find that! Haha

2021-01-07 16:05 UTC, merged