[DX-1861] Update node messaging
Bandwidth/bandwidth.github.io pull request #622
Opened 2021-03-04 21:53 UTC by hamermike

2021-03-04 22:00 UTC, jmulford-bw approved these changes

2021-03-04 22:03 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-update-node-messaging.s3-website-us-east-1.amazonaws.com/index.html

2021-03-04 22:16 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-update-node-messaging.s3-website-us-east-1.amazonaws.com/index.html

2021-03-04 22:19 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-update-node-messaging.s3-website-us-east-1.amazonaws.com/index.html

2021-03-04 22:22 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-update-node-messaging.s3-website-us-east-1.amazonaws.com/index.html

2021-03-05 13:48 UTC, ajrice6713 requested changes

2021-03-05 13:48 UTC, ajrice6713 commented on guides/sdks/node/usage-guide-messaging.md
> +const response = await controller.createMessage('user-id-123', {
Shouldn't this be `accountId`

2021-03-05 13:48 UTC, ajrice6713 commented on guides/sdks/node/usage-guide-messaging.md
> +var response = await controller.createMessage("user-id-123", body);
Same here - `accountId`

2021-03-05 14:04 UTC, hamermike commented on guides/sdks/node/usage-guide-messaging.md
> +var response = await controller.createMessage("user-id-123", body);
Old file that I accidentally added, it wasn't being linked to. Good catch.

2021-03-05 14:07 UTC, ajrice6713 approved these changes

2021-03-05 14:09 UTC, DX-Bandwidth commented
Preview Changes at:
        http://bw-dev-update-node-messaging.s3-website-us-east-1.amazonaws.com/index.html

2021-03-09 15:18 UTC, merged