Update decttion result details
Bandwidth/bandwidth.github.io pull request #719
Opened 2021-11-11 19:45 UTC by tmoney-bw

## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

Add links for machine detection result types
Correct example response

2021-11-11 19:52 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-11 20:36 UTC, nashley commented on voice/bxml/callbacks/about.md
> +| [Machine Detection Complete](machineDetectionComplete.md)   | Bandwidth API sends this when the result of a machine detection request is available. |
I'd line up the `|`, but you really don't need to

2021-11-11 20:36 UTC, nashley commented on voice/bxml/callbacks/answer.md
> +| machineDetectionResult | (optional) if a sync machine detection operation was requested, the result of the operation will be sent here. Possible values are the same as for the async webhook [Machin
```suggestion
| machineDetectionResult | (optional) if [machine detection was requested](../../methods/calls/postCalls.md#machine-detection-request) in `sync` mode, the result will be specified here. Possible values are the same as the async counterpart: [Machine Detection Complete](machineDetectionComplete.md) |
```
Not sure if my suggested link works, but I think it should.
I still don't like `webhook`.

2021-11-11 21:40 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-11 22:07 UTC, nashley approved these changes
I confirmed the links work

2021-11-11 22:13 UTC, nashley requested changes
Example is incorrect

2021-11-12 13:33 UTC, ajrice6713 submitted a review, later dismissed

2021-11-12 13:34 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-12 17:20 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-12 20:12 UTC, nashley approved these changes

2021-11-12 20:14 UTC, nashley requested changes
Bad json

2021-11-12 20:28 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-12 20:29 UTC, DX-Bandwidth commented
http://bw-gitbook-api-docs-vapi-1-update-amd-docs.s3-website-us-east-1.amazonaws.com/

2021-11-12 21:09 UTC, nashley approved these changes
Indentation is still inconsistent, but whatever

2021-11-12 21:30 UTC, vsmith-bw approved these changes

2021-11-12 21:30 UTC, merged